# submariner-config-cluster-a.yaml
# Purpose: Configures Submariner for Cluster A (AWS).
# ACM reads this to prepare the cloud environment (open security group rules for IPsec)
# and designate gateway node(s) on the managed cluster.
apiVersion: submarineraddon.open-cluster-management.io/v1alpha1
kind: SubmarinerConfig
metadata:
  name: submariner
  namespace: cluster-a
  labels:
    app.kubernetes.io/part-of: demo-app
spec:
  gatewayConfig:
    gateways: 1
  IPSecNATTPort: 4500
  NATTEnable: true
  cableDriver: libreswan
  loadBalancerEnable: true
  credentialsSecret:
    name: cluster-a-cloud-creds
